# Generated by Django 4.2.4 on 2023-12-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EconomicIndicator',
            new_name='CofferModel',
        ),
    ]
