# Generated by Django 4.2.4 on 2024-01-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_coffermodel_added_alter_coffermodel_insight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffermodel',
            name='country',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coffermodel',
            name='impact',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coffermodel',
            name='insight',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coffermodel',
            name='pestle',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coffermodel',
            name='region',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coffermodel',
            name='sector',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coffermodel',
            name='source',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coffermodel',
            name='title',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coffermodel',
            name='topic',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
